#spring.application.name=ecom-application
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.show-sql=true #Habilita log
#spring.jpa.hibernate.ddl-auto=create #Automaticamente cria tabela jpa Não usar em prod

spring:
  application:
    name: ecom-application
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create